import Head from "next/head";
import Navbar from "../components/navbar/Navbar";

export default function AccountPage() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="flex h-full w-full flex-col bg-inherit">
        <h1>Belom, Mager</h1>
      </div>
    </>
  );
}
