import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import { trpc } from "../utils/trpc";
import { Box, Center, Flex, Grid, GridItem, Heading, Stack, Text, useColorModeValue } from "@chakra-ui/react";
import Navbar from "../components/navbar/Navbar";
import Note from "../components/note/Note";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box display={'flex'} flexDirection='column' bgGradient={useColorModeValue('linear(to-r,#3a7bd5,#3a6073)', 'gray.900')} w={'full'} className='h-screen' textColor={'white'}>
        <Navbar />
        <Heading size={'2xl'} p={2} className='underline'>
          Notes
        </Heading>
        <Box as="div" className="w-full h-full p-2 flex flex-col transition-all lg:grid lg:grid-cols-5 gap-3">
          <Note />
          <Note />
          <Note />
          <Note />
          <Note />
          <Note />
          <Note />
          <Note />
          <Note />
          <Note />

        </Box>
      </Box>
    </>
  );
};

export default Home;

